Output output.gif

Set Theme "TokyoNight"
Set FontSize 18
Set Width 1100
Set Height 640
Set Padding 30
Set TypingSpeed 60ms
Set PlaybackSpeed 1.0
Set Shell zsh

Hide
Type "export PS1='%F{141}abhi0x%f@%F{117}github%f %F{215}~%f $ '"
Enter
Type "alias whoami='echo abhishek mourya'"
Enter
Type "clear"
Enter
Show

Sleep 800ms

Type "whoami"
Sleep 200ms
Enter
Sleep 1000ms

Type "./welcome.sh"
Sleep 200ms
Enter

Sleep 3800ms

Type "echo 'ship > perfect'"
Sleep 200ms
Enter

Sleep 2500ms
